name: build
on:
  push:
    tags:
      - v*
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/stealthrocket
  GH_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: crate-ci/typos@master
      with:
        files: '*.go'
        write_changes: true

  golangci-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com.insteadOf https://github.com
      - run: go mod download
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout 5m

  python-lint:
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Go tip
      run: |
        curl -sL https://storage.googleapis.com/go-build-snap/go/linux-amd64/$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1;}').tar.gz -o gotip.tar.gz
        ls -lah gotip.tar.gz
        mkdir -p $HOME/gotip
        tar -C $HOME/gotip -xzf gotip.tar.gz

    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com.insteadOf https://github.com
    - run: make testdata GO=$HOME/gotip/bin/go
    - run: make test GO=$HOME/gotip/bin/go
