name: docker
on:
  push:
    tags:
      - v*
    branches:
    - main

env:
  GOPRIVATE: github.com/stealthrocket
  GH_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

jobs:
  docker-build:
    env:
      PAT_PACKAGES: ${{ secrets.PAT_PACKAGES }}
      BUILDPLATFORM: "linux/amd64,linux/arm64"
    name: Container Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true
    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com.insteadOf https://github.com
    - run: echo $PAT_PACKAGES | docker login ghcr.io -u USERNAME --password-stdin
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      run: make docker-buildx
